src/Entity/EntitreeLocation.php
<?php

namespace Drupal\entitree\Entity;

use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\entitree\EntitreeLocationInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\Cache;

/**
 * Defines the EntitreeLocation entity.
 *
 * @ContentEntityType(
 *   id = "entitree_location",
 *   label = @Translation("Entitree Location"),
 *   handlers = {
 *     "form" = {
 *       "add" = "Drupal\entitree\Form\EntitreeLocationForm",
 *       "edit" = "Drupal\entitree\Form\EntitreeLocationForm"
 *     },
 *   "list_builder" = "Drupal\Core\Entity\EntityListBuilder"
 *   },
 *   entity_keys = {
 *     "id" = "id",
 *     "uuid" = "uuid"
 *   },
 *   base_table = "entitree_location",
 *   admin_permission = "administer entitree"
 * )
 */
class EntitreeLocation extends ContentEntityBase implements EntitreeLocationInterface {

  /**
   * Path segment for this location at the time it was loaded by the store.
   *
   * @var string
   */
  protected $originalPathSegment;

  /**
   * The parent location when this location was loaded.
   *
   * @var \Drupal\entitree\EntitreeLocationInterface
   */
  protected $originalParentLocation = NULL;

  /**
   * The parent location.
   *
   * @var \Drupal\entitree\EntitreeLocationInterface
   */
  protected $parentLocation = NULL;

  /**
   * Identifies if this location is the site root.
   *
   * @var bool
   */
  protected $siteRoot = NULL;

  /**
   * Identifies if this location is the Entitree root.
   *
   * @var bool
   */
  protected $entitreeRoot = FALSE;

  /**
   * {@inheritDoc}
   */
  public static function baseFieldDefinitions(
    EntityTypeInterface $entity_type
  ) {
    $fields['id'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('ID'))
      ->setDescription(t('The ID of the entitree location entity.'))
      ->setRequired(TRUE)
      ->setReadOnly(TRUE);

    // Unique beyond the scope of Entitree.
    $fields['uuid'] = BaseFieldDefinition::create('uuid')
      ->setLabel(t('UUID'))
      ->setDescription(t('The UUID of the entitree location entity.'))
      ->setRequired(TRUE)
      ->setReadOnly(TRUE);

    $fields['label'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Label'))
      ->setDescription(t('The label of the entitree location entity.'))
      ->setRequired(TRUE)
      ->setReadOnly(FALSE);

    $fields['main_location'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Main Location'))
      ->setDescription(t('Flag to denote the main location for an entity'))
      ->setRequired(TRUE)
      ->setDefaultValue(FALSE);

    $fields['path_segment'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Path segment'))
      ->setDescription(
        t('The path segment of the entitree location entity.')
      )
      ->setReadOnly(FALSE);

    $fields['pid'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('PID'))
      ->setDescription(
        t('The PID path_alias reference of the entitree location entity.')
      )
      ->setReadOnly(FALSE);

    $fields['ref_entity_id'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Referenced entity id'))
      ->setDescription(
        t('The referenced entity id of the entitree location entity.')
      )
      ->setRequired(TRUE)
      ->setReadOnly(FALSE);

    $fields['ref_entity_type'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Referenced entity type'))
      ->setDescription(
        t('The referenced entity type of the entitree location entity.')
      )
      ->setRequired(TRUE)
      ->setReadOnly(FALSE);

    $fields['langcode'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Language'))
      ->setRequired(TRUE)
      ->setReadOnly(TRUE);

    return $fields;
  }

  /**
   * {@inheritDoc}
   */
  public function getId(): int {
    return (int) $this->get('id')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getLabel(): string {
    return $this->get('label')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getOriginalParent(): ?EntitreeLocationInterface {
    return $this->originalParentLocation;
  }

  /**
   * {@inheritDoc}
   */
  public function getParent(): ?EntitreeLocationInterface {
    return $this->parentLocation;
  }

  /**
   * {@inheritDoc}
   */
  public function setOriginalparent(?EntitreeLocationInterface $parent) {
    $this->originalParentLocation = $parent;
  }

  /**
   * {@inheritDoc}
   */
  public function setParent(?EntitreeLocationInterface $parent) {
    $this->parentLocation = $parent;
  }

  /**
   * {@inheritDoc}
   */
  public function parentHasChanged(): bool {
    $originalParent = $this->getOriginalParent();
    $parent = $this->getParent();
    return !$originalParent || $parent->getId() !== $originalParent->getId();
  }

  /**
   * {@inheritDoc}
   */
  public function getPathSegment(): string {
    return $this->get('path_segment')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getOriginalPathSegment(): string {
    return $this->originalPathSegment;
  }

  /**
   * {@inheritDoc}
   */
  public function pathSegmentHasChanged(): bool {
    return $this->getPathSegment() !== $this->getOriginalPathSegment();
  }

  /**
   * {@inheritDoc}
   */
  public function getLangcode(): string {
    return $this->get('langcode')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getReferencedEntityType(): string {
    return $this->get('ref_entity_type')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getReferencedEntityId(): int {
    return (int) $this->get('ref_entity_id')->getString();
  }

  /**
   * {@inheritDoc}
   */
  public function getReferencedEntity(): EntityInterface {
    return \Drupal::entityTypeManager()
      ->getStorage(
        $this->getReferencedEntityType()
      )->load(
        $this->getReferencedEntityId()
      );
  }

  /**
   * {@inheritDoc}
   */
  public function isSiteRoot(): bool {
    return $this->siteRoot !== NULL ? $this->siteRoot : $this->isHome();
  }

  /**
   * {@inheritDoc}
   */
  public function setSiteRoot(bool $value): EntitreeLocationInterface {
    $this->siteRoot = $value;
    return $this;
  }

  /**
   * {@inheritDoc}
   */
  public function isEntitreeRoot(): bool {
    return $this->entitreeRoot;
  }

  /**
   * {@inheritDoc}
   */
  public function setEntitreeRoot(bool $value): EntitreeLocationInterface {
    $this->entitreeRoot = $value;
    return $this;
  }

  /**
   * {@inheritDoc}
   */
  public function isHome(): bool {
    return \Drupal::state()->get('entitree.site_root_location') == $this->getId();
  }

  /**
   * {@inheritDoc}
   */
  public function isMainLocation(): bool {
    return (int) $this->get('main_location')->getString() === 1;
  }

  /**
   * Determine if this location has already been added to the tree.
   *
   * @return bool
   *   TRUE if added to the tree. FALSE if not added to the tree.
   */
  protected function hasBeenAddedToTree(): bool {
    // For now assume any location without an original parent hasn't been added.
    return !!$this->getOriginalParent() || $this->isSiteRoot();
  }

  /**
   * {@inheritDoc}
   */
  public function getChildren(): array {
    if (!$this->hasBeenAddedToTree()) {
      return [];
    }

    // Load and return the children from the store.
    return \Drupal::service('entitree.manager')
      ->getStore($this->getLangcode())
      ->getLocationChildren($this);
  }

  /**
   * {@inheritDoc}
   */
  public function getAncestors(): array {
    return \Drupal::service('entitree.manager')
      ->getStore($this->getLangcode())
      ->getLocationAncestors($this->getId());
  }

  /**
   * {@inheritDoc}
   */
  public function getPath(): string {
    if ($this->isSiteRoot()) {
      return '/';
    }

    $result = \Drupal::service("database")
      ->query("SELECT alias from {path_alias} where id = :pid", [
        ":pid" => $this->get('pid')->getString(),
      ])->fetchObject();

    // The site root returns only a slash.
    if (isset($result->alias)) {
      return $result->alias;
    }
    return '/';
  }

  /**
   * Generate and return the full path string to this location.
   *
   * This by default does not use pending path segments and should match the
   * path currently saved in the database.
   *
   * @return string
   *   The full path of this location.
   */
  protected function generatePath(): string {
    // The site root is always /.
    if ($this->isSiteRoot()) {
      return '/';
    }

    // Get the parent's path.
    $parentPath = '';
    if ($this->getParent()) {
      $parentPath = $this->getParent()->getPath();
    }

    $path = $parentPath === '/'
      ? $parentPath . $this->getPathSegment()
      : $parentPath . "/" . $this->getPathSegment();

    return $path;
  }

  /**
   * {@inheritDoc}
   */
  public function updatePathAlias() {
    // Only generate a path alias if this location has a path segment.
    if ($this->getPathSegment()) {
      $path = $this->generatePath();

      // Update path alias.
      $entitreeEntityTypeManager = \Drupal::service('plugin.manager.entitree_entity_type');
      $plugin = $entitreeEntityTypeManager
        ->getEntitreeEntityType($this->getReferencedEntityType());

      /*
       * TODO figure out approach for proper language code handling.
       */
      $pid = $this->get('pid')->getString();
      if ($pid) {
        $pathAlias = \Drupal::entityTypeManager()->getStorage('path_alias')->load($pid);
        $pathAlias->alias = $path;
        $pathAlias->save();
      }
      else {
        $pathAlias = \Drupal::entityTypeManager()->getStorage('path_alias')
          ->create([
            'path' => $plugin->getSourcePath($this->getReferencedEntityId()),
            'alias' => $path,
            'langcode' => $this->getLangcode(),
          ]);
        $pathAlias->save();

templates/entitree--location-operations.html.twig
<div class="entitree-location-operations">
  <span class="entitree-location-operations-icon"></span>
  <div class="entitree-location-operations-inner">
    {% for operation in operations %}
      <a href="{{ operation.url }}" class="btn entitree--operation-button">{{ operation.label }}</a>
    {% endfor %}
  </div>
</div>

templates/entitree--manage-locations.html.twig
<section class="entitree-locations-current">
    <h2>Current Locations</h2>
    <table>
        <thead>
            <tr>
                <th>Label</th>
                <th>Parent</th>
                <th>Path</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            {% for location in locations %}
                <tr class='entitree-locations-location {% if location.main_location.value %}main-location{% endif %}'>
                    <td>{{ location.label.value }}</td>
                    <td>
                      {% for ancestor in location.ancestors %}
                        {{ ancestor.label.value }}
                        {% if loop.last == false %}
                            >
                        {% endif %}
                      {% endfor %}
                    </td>
                    <td><span class='parent-path'>{{ location.parent.getPath() }}{% if location.parent.getPath != '/' %}/{% endif %}</span>{{ location.path_segment.value }}</td>
                    <td class='location'>
                        {{ entitree_location_operations(location) }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

templates/entitree--tree-display.html.twig
<div class="entitree--tree-display">
    <div class="entitree-tree-header">
        <div class="entitree-page-help">{{ pageHelp }}</div>
    </div>

    <section class="entitree--tree-display--row entitree--tree-path">
        {% for location in ancestors %}
            {% set browseParameters = destination.browse.parameters|merge({"parent":location.id.value}) %}
            <div class="location location-ancestor {% if location.main_location.value %}main-location{% endif %}">
                <a href="{{ path(destination.browse.route, browseParameters) }}" title="{{location.getPath()}}">{{ location.label.value }}</a>
                {{ entitree_location_operations(location, destination) }}
            </div>
        {% endfor %}

        <div class="location location-ancestor location-parent {% if parent.main_location.value %}main-location{% endif %}">
            <span title="{{parent.getPath()}}">{{ parent.label.value }}</span>
            {{ entitree_location_operations(parent, destination) }}
        </div>
    </section>
    <h2 class="entitree--subhead">Children</h2>
    <section class="entitree--tree-display--row entitree--tree-children">
        {% for location in children %}
            {% set browseParameters = destination.browse.parameters|merge({"parent":location.id.value}) %}

            <div class="location location-child {% if location.main_location.value %}main-location{% endif %}">
                {# Don't allow user to browse into the location currently being edited because they can't select a parent that's currently a descendant of the location being edited #}
                {% if activeLocation and activeLocation.id.value == location.id.value %}
                  {{ location.label.value }}
                {% else %}
                  <a href="{{ path(destination.browse.route, browseParameters) }}" title="{{location.getPath()}}">{{ location.label.value }}</a>
                {% endif %}
                {{ entitree_location_operations(location, destination) }}
            </div>
        {% endfor %}
    </section>
</div>